var minionsList = [
    {
      "Name": "Alakazam",
      "Type": "psychic",
      "Attack1Name": "Psychic",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Dream Eater",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainst": "dark",
      "StrongAgainst": "fighting",
      "Img": "../images/Alakazam.png"
    },
    {
      "Name": "Arcanine",
      "Type": "fire",
      "Attack1Name": "Fire Blast",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Superpower",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainst": "water",
      "StrongAgainst": "grass",
      "Img": ""
    },
    {
      "Name": "Articuno",
      "Type": "ice",
      "Attack1Name": "Sky Attack",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Ice Beam",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainst": "fire",
      "StrongAgainst": "grass",
      "Img": ""
    },
    {
      "Name": "Chansey",
      "Type": "normal",
      "Attack1Name": "Hyper Beam",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Double-Edge",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainst": "none",
      "StrongAgainst": "none",
      "Img": ""
    },
    {
      "Name": "Flareon",
      "Type": "fire",
      "Attack1Name": "Flare Blitz",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Fire Blast",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainst": "water",
      "StrongAgainst": "grass",
      "Img": ""
    },
    {
      "Name": "Gengar",
      "Type": "ghost",
      "Attack1Name": "Dream Eater",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Shadow Ball",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainst": "ghost",
      "StrongAgainst": "psychic",
      "Img": ""
    },
    {
      "Name": "Gyarados",
      "Type": "water",
      "Attack1Name": "Ice Beam",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Blizzard",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainst": "grass",
      "StrongAgainst": "fire",
      "Img": ""
    },
    {
      "Name": "Jolteon",
      "Type": "electric",
      "Attack1Name": "Thunder",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Pay Day",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainst": "ground",
      "StrongAgainst": "water",
      "Img": ""
    },
    {
      "Name": "Lapras",
      "Type": "water",
      "Attack1Name": "Megahorn",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Hydro Pump",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainst": "grass",
      "StrongAgainst": "fire",
      "Img": ""
    },
    {
      "Name": "Machamp",
      "Type": "fighting",
      "Attack1Name": "Bulk Up",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Earthquake",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainst": "psychic",
      "StrongAgainst": "ice",
      "Img": ""
    },
    {
      "Name": "Marowak",
      "Type": "ground",
      "Attack1Name": "Bonemerang",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Headbutt",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainst": "water",
      "StrongAgainst": "fire",
      "Img": ""
    },
    {
      "Name": "Moltres",
      "Type": "flying",
      "Attack1Name": "Sky Attack",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Heat Wave",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainst": "ice",
      "StrongAgainst": "fighting",
      "Img": ""
    },
    {
      "Name": "Nidoqueen",
      "Type": "poison",
      "Attack1Name": "Sludge Bomb",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Shadow Ball",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainst": "psychic",
      "StrongAgainst": "grass",
      "Img": ""
    },
    {
      "Name": "Ninetails",
      "Type": "fire",
      "Attack1Name": "Fire Blast",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Flamethrower",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainst": "water",
      "StrongAgainst": "grass",
      "Img": ""
    },
    {
      "Name": "Poliwhirl",
      "Type": "water",
      "Attack1Name": "Hydro Pump",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Bubble Beam",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainst": "electric",
      "StrongAgainst": "fire",
      "Img": ""
    },
    {
      "Name": "Rapidash",
      "Type": "fire",
      "Attack1Name": "Fire Blast",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Flare Blitz",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainst": "water",
      "StrongAgainst": "grass",
      "Img": ""
    },
    {
      "Name": "Snorlax",
      "Type": "normal",
      "Attack1Name": "Pay Day",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Body Slam",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainst": "none",
      "StrongAgainst": "none",
      "Img": ""
    },
    {
      "Name": "Vaporeon",
      "Type": "water",
      "Attack1Name": "Surf",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Blizzard",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainst": "grass",
      "StrongAgainst": "fire",
      "Img": ""
    },
    {
      "Name": "Zapdos",
      "Type": "electric",
      "Attack1Name": "Sky Attack",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Thunder",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainst": "ground",
      "StrongAgainst": "water",
      "Img": ""
    }
  ]

module.exports = {
    minionsList: minionsList
}
