var minionsList = [
    {
      "Name": "Alakazam",
      "Type": "../images/psychicOrb.png",
      "Attack1Name": "Psychic",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Blast",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainstImg": "../images/darkOrb.png",
      "StrongAgainstImg": "../images/fightingOrb.png",
      "Img": "../images/Alakazam.png"
    },
    {
      "Name": "Arcanine",
      "Type": "../images/fireOrb.png",
      "Attack1Name": "Fire Blast",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Superpower",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainstImg": "../images/waterOrb.png",
      "StrongAgainstImg": "../images/grassOrb.png",
      "Img": "../images/Arcanine.jpg"
    },
    {
      "Name": "Articuno",
      "Type": "../images/iceOrb.png",
      "Attack1Name": "Sky Attack",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Ice Beam",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainstImg": "../images/fireOrb.png",
      "StrongAgainstImg": "../images/grassOrb.png",
      "Img": "../images/Articuno.jpg"
    },
    {
      "Name": "Chansey",
      "Type": "normal",
      "Attack1Name": "Hyper Beam",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Double-Edge",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainstImg": "none",
      "StrongAgainstImg": "none",
      "Img": "../images/Chansey.jpg"
    },
    {
      "Name": "Flareon",
      "Type": "../images/fireOrb.png",
      "Attack1Name": "Flare Blitz",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Fire Blast",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainstImg": "../images/waterOrb.png",
      "StrongAgainstImg": "../images/grassOrb.png",
      "Img": "../images/Flareon.jpg"
    },
    {
      "Name": "Gengar",
      "Type": "../images/ghostOrb.png",
      "Attack1Name": "Dream Eater",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Shadow Ball",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainstImg": "../images/ghostOrb.png",
      "StrongAgainstImg": "../images/psychicOrb.png",
      "Img": "../images/Gengar.png"
    },
    {
      "Name": "Gyarados",
      "Type": "../images/waterOrb.png",
      "Attack1Name": "Ice Beam",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Blizzard",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainstImg": "../images/grassOrb.png",
      "StrongAgainstImg": "../images/fireOrb.png",
      "Img": "../images/gyrarados.jpeg"
    },
    {
      "Name": "Jolteon",
      "Type": "../images/electricOrb.png",
      "Attack1Name": "Thunder",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Pay Day",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainstImg": "../images/groundOrb.png",
      "StrongAgainstImg": "../images/waterOrb.png",
      "Img": "../images/Jolteon.jpg"
    },
    {
      "Name": "Lapras",
      "Type": "../images/waterOrb.png",
      "Attack1Name": "Megahorn",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Hydro Pump",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainstImg": "../images/grassOrb.png",
      "StrongAgainstImg": "../images/fireOrb.png",
      "Img": "../images/Lapras.png"
    },
    {
      "Name": "Machamp",
      "Type": "../images/fightingOrb.png",
      "Attack1Name": "Bulk Up",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Earthquake",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainstImg": "../images/psychicOrb.png",
      "StrongAgainstImg": "../images/iceOrb.png",
      "Img": "../images/machamp.jpg"
    },
    {
      "Name": "Marowak",
      "Type": "../images/groundOrb.png",
      "Attack1Name": "Bonemerang",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Headbutt",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainstImg": "../images/waterOrb.png",
      "StrongAgainstImg": "../images/fireOrb.png",
      "Img": "../images/Marowak.jpg"
    },
    {
      "Name": "Moltres",
      "Type": "flying",
      "Attack1Name": "Sky Attack",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Heat Wave",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainstImg": "../images/iceOrb.png",
      "StrongAgainstImg": "../images/fightingOrb.png",
      "Img": "../images/Moltres.jpg"
    },
    {
      "Name": "Nidoqueen",
      "Type": "poison",
      "Attack1Name": "Sludge Bomb",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Shadow Ball",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainstImg": "../images/psychicOrb.png",
      "StrongAgainstImg": "../images/grassOrb.png",
      "Img": "../images/nidoqueen.jpg"
    },
    {
      "Name": "Ninetails",
      "Type": "../images/fireOrb.png",
      "Attack1Name": "Fire Blast",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Flamethrower",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainstImg": "../images/waterOrb.png",
      "StrongAgainstImg": "../images/grassOrb.png",
      "Img": "../images/Ninetails.png"
    },
    {
      "Name": "Poliwhirl",
      "Type": "../images/waterOrb.png",
      "Attack1Name": "Hydro Pump",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Bubble Beam",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainstImg": "../images/electricOrb.png",
      "StrongAgainstImg": "../images/fireOrb.png",
      "Img": "../images/Poliwhirl.jpg"
    },
    {
      "Name": "Rapidash",
      "Type": "../images/fireOrb.png",
      "Attack1Name": "Fire Blast",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Flare Blitz",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainstImg": "../images/waterOrb.png",
      "StrongAgainstImg": "../images/grassOrb.png",
      "Img": "../images/Rapidash.jpg"
    },
    {
      "Name": "Snorlax",
      "Type": "normal",
      "Attack1Name": "Pay Day",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Body Slam",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainstImg": "none",
      "StrongAgainstImg": "none",
      "Img": "../images/Snorlax.jpg"
    },
    {
      "Name": "Vaporeon",
      "Type": "../images/waterOrb.png",
      "Attack1Name": "Surf",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Blizzard",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainstImg": "../images/grassOrb.png",
      "StrongAgainstImg": "../images/fireOrb.png",
      "Img": "../images/vaporeon.jpg"
    },
    {
      "Name": "Zapdos",
      "Type": "../images/electricOrb.png",
      "Attack1Name": "Sky Attack",
      "Attack1Power": 6,
      "Attack1Cost": 9,
      "Attack2Name": "Thunder",
      "Attack2Power": 9,
      "Attack2Cost": 13,
      "Health": 20,
      "WeakAgainstImg": "../images/groundOrb.png",
      "StrongAgainstImg": "../images/waterOrb.png",
      "Img": "../images/Zapdos.jpg"
    }
  ]

module.exports = {
    minionsList: minionsList
}
